const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),proof=fs.readFileSync(path.join(root,'assets/lb-running-service-proof-v1.js'),'utf8');
const map=fs.readFileSync(path.join(root,'vps/map-v2/public/carte-core-preview.html'),'utf8'),core=fs.readFileSync(path.join(root,'assets/lb-index-core.js'),'utf8');
test('map and application embed the same evidence rule without another script request',()=>{assert.ok(core.includes(proof));assert.ok(map.includes(proof));assert.ok(!map.includes('<script src="./lb-running-service-proof'));assert.ok(!core.includes("id: 'sncf-carte'"));assert.ok(!map.includes('const sncfPromise = loadSncfRealtime'));assert.ok(!map.includes('sncfPromise.finally'));});
function context(){let count=0;const ctx={Map,WeakMap,Date,realtimeRawData:{},stopsById:new Map([['m',{name:'Metz'}],['t',{name:'Thionville'}],['l',{name:'Luxembourg'}]]),parseGtfsRtTimestamp:x=>Date.parse(x),normalizeTrainNumberKey:String,normalizeStationName:x=>{count++;return String(x).toLowerCase()}};vm.createContext(ctx);vm.runInContext(map.slice(map.indexOf('  /* LB_RUNNING_SERVICE_PROOF_V1_START */'),map.indexOf('  /* LB_RUNNING_SERVICE_PROOF_V1_END */')),ctx);return {ctx,normalizations:()=>count};}
const seq=[{stop_id:'m'},{stop_id:'t'},{stop_id:'l'}];
function feed(status='ON_TIME',stops={Metz:0,Thionville:0,Luxembourg:0},options={}){return {generated_at:options.date||new Date().toISOString(),trains:{88714:{status,data_source:options.source||'gtfs_rt',stops,canceled_stops:options.canceled||[]}}};}
test('fallback map proof preserves full-route freshness and explicit source checks',()=>{const {ctx}=context();ctx.realtimeRawData.gtfs=feed();assert.equal(ctx.lbMapRunningServiceState('trip',seq,'88714').status,'ON_TIME');ctx.realtimeRawData.gtfs=feed('DELAYED',{Metz:0,Thionville:3,Luxembourg:5});assert.equal(ctx.lbMapRunningServiceState('trip',seq,'88714').maxDelay,5);for(const status of ['CANCELED','PARTIAL_CANCELLATION','SCHEDULED']){ctx.realtimeRawData.gtfs=feed(status);assert.equal(ctx.lbMapRunningServiceState('trip',seq,'88714'),null);}for(const options of [{date:new Date(Date.now()-360000).toISOString()},{date:new Date(Date.now()+120000).toISOString()},{source:'cfl-hafas'},{canceled:['Metz']}]){ctx.realtimeRawData.gtfs=feed('ON_TIME',undefined,options);assert.equal(ctx.lbMapRunningServiceState('trip',seq,'88714'),null);}ctx.realtimeRawData.gtfs=feed('ON_TIME',{Metz:0,Thionville:0});assert.equal(ctx.lbMapRunningServiceState('trip',seq,'88714'),null);});
test('map caches proof until a new feed or service sequence, without renormalizing each animation frame',()=>{const {ctx,normalizations}=context();ctx.realtimeRawData.gtfs=feed();const first=ctx.lbMapRunningServiceState('trip',seq,'88714'),count=normalizations();for(let i=0;i<10000;i++)assert.equal(ctx.lbMapRunningServiceState('trip',seq,'88714'),first);assert.equal(normalizations(),count);ctx.realtimeRawData.gtfs=feed('DELAYED',{Metz:0,Thionville:1,Luxembourg:2});assert.equal(ctx.lbMapRunningServiceState('trip',seq,'88714').maxDelay,2);assert.ok(normalizations()>count);});
