const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const code=fs.readFileSync(path.join(__dirname,'../assets/lb-index-features.js'),'utf8');
function setup(fetch){const body={textContent:'',innerHTML:''},host={open:false,dataset:{},querySelector:()=>body},state={requestId:1};const ctx={Map,Set,Date,URL,URLSearchParams,AbortController,setTimeout,clearTimeout,state,fetch,byId:()=>host,safe:s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))};vm.createContext(ctx);vm.runInContext(code.slice(code.indexOf('  const profileEventsCache ='),code.indexOf('  function renderDisruption(')),ctx);return {ctx,host,body,state};}
const event=(extra={})=>({title:'Incident',text:'Détail',sources:['GTFS-RT','SIRI-SX'],state:'active',operational:true,...extra});
test('profile shows active/upcoming map sources, removes repeated main API cause and duplicates',()=>{const {ctx}=setup();const rows=ctx.profileEventRows({events:[event(),event(),event({state:'ended'}),event({operational:false}),event({sources:['UNKNOWN']}),event({title:'Réutilisation',sources:['API-SNCF']}),event({title:'Travaux en cours.',state:'upcoming',operational:false})]},'Réutilisation');assert.equal(rows.length,2);const html=ctx.profileEventsHTML({events:rows},'');assert.match(html,/Travaux à venir/);assert.match(html,/À VENIR/);});
test('profile escapes external messages and only renders HTTP links',()=>{const {ctx}=setup();const html=ctx.profileEventsHTML({events:[event({title:'<img onerror=alert(1)>',text:'<script>boom</script>',links:[{url:'javascript:alert(1)'},{url:'https://example.com',label:'<unsafe>'}]})]},'');assert.ok(!html.includes('<script>'));assert.ok(!html.includes('<img'));assert.ok(!html.includes('javascript:'));assert.match(html,/&lt;unsafe&gt;/);assert.match(html,/noopener noreferrer/);});
test('disclosure is lazy, shares rapid reopen and uses cached response',async()=>{let count=0,resolve;const {ctx,host}=setup(()=>{count++;return new Promise(r=>resolve=r)});ctx.setupProfileEvents('88715','2026-10-08',null,{tripId:'trip'},1,false);assert.equal(count,0);host.open=true;const pending=host.ontoggle();await host.ontoggle();assert.equal(count,1);resolve({ok:true,json:async()=>({ok:true,events:[event()]})});await pending;await host.ontoggle();assert.equal(count,1);});
test('late response for previous train cannot replace current train content',async()=>{let resolve;const {ctx,host,body,state}=setup(()=>new Promise(r=>resolve=r));ctx.setupProfileEvents('88715','2026-10-08',null,null,1,false);host.open=true;const pending=host.ontoggle();state.requestId=2;body.innerHTML='Current train';resolve({ok:true,json:async()=>({ok:true,events:[event()]})});await pending;assert.equal(body.innerHTML,'Current train');});
test('failed traffic response can retry without affecting the base disruption card',async()=>{let count=0;const {ctx,host,body}=setup(async()=>{if(++count===1)throw Error('offline');return {ok:true,json:async()=>({ok:true,events:[]})}});ctx.setupProfileEvents('88715','2026-10-08',null,null,1,false);host.open=true;await host.ontoggle();assert.match(body.textContent,/indisponibles/);await host.ontoggle();assert.equal(count,2);assert.match(body.innerHTML,/Aucune autre perturbation/);});
