name: Maj GTFS-RT

on:
  schedule:
    - cron: "*/5 * * * *"  # toutes les 5 minutes
  workflow_dispatch:

jobs:
  maj-retards:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Python + dépendances
        run: |
          python3 -m pip install --upgrade pip
          pip install gtfs-realtime-bindings requests

      - name: Exécuter le script Python
        run: python3 -u gtfs_to_json.py

      - name: Commit des données si modifiées
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Assistant-train/retards.json
          git diff --staged --quiet || (
            git commit -m "Mise à jour GTFS-RT"
            git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          )
