name: Maj GTFS-RT

on:
  schedule:
    - cron: "*/5 * * * *"  # toutes les 5 minutes
  workflow_dispatch:

jobs:
  maj-retards:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # important pour ne pas écraser ton PAT

      - name: Installer Python + dépendances
        run: |
          python3 -m pip install --upgrade pip
          pip install gtfs-realtime-bindings requests

      - name: Exécuter le script Python
        run: python3 -u gtfs_to_json.py

          - name: Commit des données si modifiées
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Assistant-train/retards.json
          if ! git diff --staged --quiet; then
            git commit -m "Mise à jour GTFS-RT"
            git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:main
          else
            echo "Pas de changement à pousser"
          fi
