name: Maj SIRI SX Alertes

on:
  schedule:
    - cron: "*/5 * * * *"  # toutes les 5 minutes
  workflow_dispatch:

jobs:
  maj-siri-sx:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configurer Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Mettre à jour la branche locale avec la branche distante
        run: git pull --rebase

      - name: Installer Python + dépendances
        run: |
          python3 -m pip install --upgrade pip
          pip install requests

      - name: Exécuter le script Python
        run: python3 -u AlertesSIRI.py

      - name: Ajouter et committer les changements si présents
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git add Assistant-train/siri_sx_alertes.json
          if ! git diff --staged --quiet; then
            git commit -m "Mise à jour SIRI SX alertes"
            git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:main
          else
            echo "Pas de changement à pousser"
                  fi
