name: Générer tripUpdates.json depuis openov.lu

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures
  workflow_dispatch:      # Lancement manuel possible

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Installer Python et les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install gtfs-realtime-bindings requests

    - name: Télécharger et convertir le fichier GTFS-RT
      run: |
        python parse_tripupdates.py

    - name: Commit & push tripUpdates_full.json si modification
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add tripUpdates_full.json
        if git diff --cached --quiet; then
          echo "Aucune modification à committer"
        else
          git commit -m "⏱️ Mise à jour automatique de tripUpdates_full.json"
          git push
        fi
