name: Test PAT Push

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a test file
        run: echo "Test push at $(date)" > test.txt

      - name: Commit and push test file
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b test-pat
          git add test.txt
          git commit -m "Test push from GitHub Actions"
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} test-pat
